config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home'

  resources :pages do
    collection do
      get :how_to_vote
      get :thanks
      get :duplicate_check # 不要
      get :summary
      get :ranking
      get :now_counting
    end
  end

  resources :votes, only: %i[index create] # 将来的に必要
  resources :check_vote, only: %i[index create] # :create は不要っぽい Ajaxにしたかった

  get '/practice', to: 'practice#index'

  # require 'sidekiq/web'
  # mount Sidekiq::Web => '/sidekiq'
end

app/views/shared/_footer.html.slim
.footer.page-footer.blue.lighten-4
  .container
    .row
      .col.s12.black-text.center-align
        | Powered by
        a.black-text href="http://materializecss.com"  Materialize
        / TODO: br を使ってレイアウトをしてはいけない
        br
        br
      .col.s12.black-text.center-align
        = '幻水総選挙 2018'
        / TODO: br を使ってレイアウトをしてはいけない
        br
        br

app/views/shared/_navbar.html.slim
nav.blue.lighten-4
  .container
    .row
      .col.s12
        .nav-wrapper
          a.sidenav-trigger data-target="nav-mobile" href="#"
            i.material-icons menu
          = link_to '幻水総選挙 2018 集計所', root_path, class: 'black-text'
          ul.right.hide-on-med-and-down
            li
              = link_to '#!', class: ['dropdown-trigger', 'black-text'], data: { target: 'dropdown-vote-result-desktop' } do
                | 開票結果
                i.material-icons.right
                  = 'arrow_drop_down'
            li
              = link_to '#!', class: ['dropdown-trigger', 'black-text'], data: { target: 'dropdown-vote-desktop' } do
                | 投票について
                i.material-icons.right
                  = 'arrow_drop_down'
            li
              = link_to 'Thanks', thanks_pages_path, class: 'black-text'
ul#nav-mobile.sidenav
  li
    .user-view.blue.lighten-4
      = link_to '幻水総選挙 2018 集計所', root_path, class: 'black-text'
  li
    = link_to '#!', class: ['dropdown-trigger', 'black-text'], data: { target: 'dropdown-vote-result-mobile' } do
      | 開票結果
      i.material-icons.right
        = 'arrow_drop_down'
  li
    = link_to '#!', class: ['dropdown-trigger', 'black-text'], data: { target: 'dropdown-vote-mobile' } do
      | 投票について
      i.material-icons.right
        = 'arrow_drop_down'
  li
    = link_to 'Thanks', thanks_pages_path

#dropdown-vote-desktop.dropdown-content
  li
    = link_to '投票方法', 'https://twitter.com/gensosenkyo/status/1010336071077335040', target: '_new', class: 'black-text'
  li
    = link_to '投票チェック', check_vote_index_path, class: 'black-text'

#dropdown-vote-mobile.dropdown-content
  li
    = link_to '投票方法', 'https://twitter.com/gensosenkyo/status/1010336071077335040', target: '_new', class: 'black-text'
  li
    = link_to '投票チェック', check_vote_index_path, class: 'black-text'

#dropdown-vote-result-desktop.dropdown-content
  li
    = link_to '最終順位', ranking_pages_path, class: 'black-text'
  li
    = link_to '結果概要', summary_pages_path, class: 'black-text'
  li
    = link_to '開票ツイート', now_counting_pages_path, class: 'black-text'

#dropdown-vote-result-mobile.dropdown-content
  li
    = link_to '最終順位', ranking_pages_path, class: 'black-text'
  li
    = link_to '結果概要', summary_pages_path, class: 'black-text'
  li
    = link_to '開票ツイート', now_counting_pages_path, class: 'black-text'

app/views/shared/_now_counting.html.slim
.col.s12
  h6
    = paginate @tweets, remote: true
.col.s12
  - @tweets.each_with_index do |tweet, i|
    / TODO: パーシャルに切り出す
    - user = User.find_by(id: tweet.user_id)
    - unless user.nil?
      ul.collection
        li.collection-item.avatar
          = link_to image_tag(user.profile_image_uri, class: 'circle'), user.uri, target: '_blank'
          / TODO: 25がマジックナンバーだし、式が複雑
          / ↓は降順の時に限る
          / = "No. #{(@tweets.total_count - ((@tweets.current_page - 1) * 25)) - i}"
          = "No. #{((@tweets.current_page - 1) * 25) + (i + 1)}"
          br
          .divider
          br
          = "#{user.name} ("
          = link_to "@#{user.screen_name}", user.uri, target: '_blank'
          = ") / "
          = link_to "#{time_type_to_japanese_datetime_str(tweet.tweeted_at)}", tweet.uri, target: '_blank'
          br
          br
          p
            .pre-tag-with-font
              = "#{remove_t_co_link(normalize_tweet_text(tweet.text))}"
          - if tweet.has_media
            br
            .divider
            br
            - target_tweet = Tweet.joins(:media).includes(:media).where(tweets: { tweet_number: tweet.tweet_number }).first
            / TDOO: 順番の法則がわからない……
            - target_tweet.media.order(medium_own_id: :asc).each do |medium|
              = image_tag medium.uri, width: 200
              br
.col.s12
  h6
    = paginate @tweets, remote: true

app/views/shared/_practice_tweets.html.slim
.col.s12
  h6
    = paginate @tweets, remote: true
.col.s12
  - @tweets.each_with_index do |tweet, i|
    / TODO: パーシャルに切り出す
    - user = User.find_by(id: tweet.user_id)
    - unless user.nil?
      ul.collection
        li.collection-item.avatar
          = link_to image_tag(user.profile_image_uri, class: 'circle'), user.uri, target: '_blank'
          = "No. #{@tweets.offset_value + i + 1}"
          br
          .divider
          br
          = "#{user.name} ("
          = link_to "@#{user.screen_name}", user.uri, target: '_blank'
          = ") / "
          = link_to "#{time_type_to_japanese_datetime_str(tweet.tweeted_at)}", tweet.uri, target: '_blank'
          br
          br
          p
            .pre-tag-with-font
              = "#{remove_t_co_link(normalize_tweet_text(tweet.text))}"
          - if tweet.has_media
            br
            = "（ツイートに添付画像あり）"
.col.s12
  h6
    = paginate @tweets, remote: true